### ISSUE TITLE
SRS Document

### ISSUE THREAD

**Issue by Jamesalot20** [Jamesalot20/Group-11#1]
We need to work on the SRS document. I would like to have most of this done by February 7th so we can discuss our progress with the TA. 

https://mstate-my.sharepoint.com/:w:/g/personal/jf1812_msstate_edu/EUeW_UnyCeVHoDhi8ILCY_cBmV73l01IreHkMAnbSI_Uzw?e=j1xzjK

**Comment by Jamesalot20** [comment]
4.2 through the appendix can be ignored.

**Comment by William-Emmich** [comment]
I have class from 12:30 - 5 every day except friday which I am free. Night works best for me to work on the document

**Comment by Jamesalot20** [comment]
Here is the grading rubric: 
https://mstate-my.sharepoint.com/:x:/g/personal/jf1812_msstate_edu/EUM2SfMJ9mpJoc-ie4svsBwBUlkuOv4llocBWLYS9w409A?e=6jPGq6

**Comment by JDMCCOY-dev** [comment]
I am available Monday - Friday after 5 pm. Am also available on weekends, but not in the morning.

**Comment by Jamesalot20** [comment]
I'm available Monday-Thursday after 5 and After 2 on Fridays

**Comment by JDMCCOY-dev** [comment]
#987

**Comment by William-Emmich** [comment]
SRS document finished and turned in on February 10, 2023
