### ISSUE TITLE
Buyer/Seller functions and payments

### ISSUE THREAD

**Issue by William-Emmich** [Jamesalot20/Group-11#20]

**Comment by JDMCCOY-dev** [comment]
Buyer Acceptance Testing:

1. Buyer logs in
2. Buyer adds funds to account from "Money" tab

Seller Acceptance Testing:

1. Seller logs in
2. Seller can view funds from account in "Money" tab

**Comment by William-Emmich** [comment]
Payments added May 3, 2023
